---
- name: Basic setup for local machine
  hosts: localhost

  vars:
    packages_to_install:
      - apt-file
      - autojump
      - chrony
      - fzf
      - git
      - htop
      - mosh
      - powertop
      - rsync
      - stow
      - tmux
      - trash-cli
      - wget
      # zsh
      - zsh
      # emacs
      - autoconf
      - imagemagick
      - libgccjit-12-dev
      - libglib2.0-dev
      - libgnutls28-dev
      - libgtk2.0-dev
      - libmagick++-dev
      - libncurses-dev
      - libtree-sitter-dev
      - libxft-dev
      - texinfo
      # doom
      - fd-find
      - ripgrep

    git_repos:
      - { repo: 'https://github.com/tmux-plugins/tpm.git', dest: '~/.tmux/plugins/tpm' }
      - { repo: 'https://github.com/ohmyzsh/ohmyzsh.git', dest: '~/.oh-my-zsh' }
      - { repo: 'https://github.com/zsh-users/zsh-autosuggestions.git', dest: '~/.oh-my-zsh/custom/plugins/zsh-autosuggestions' }
      - { repo: 'https://github.com/romkatv/powerlevel10k.git', dest: '~/.oh-my-zsh/custom/themes/powerlevel10k' }
      - { repo: 'https://git.savannah.gnu.org/git/emacs.git', dest: '~/workspace/applications/emacs' }
      - { repo: 'https://github.com/doomemacs/doomemacs.git', dest: '~/.config/emacs' }
    stow_items:
      - zsh
      - tmux
      # - doom
      # - regolith

  tasks:
    - name: Install packages
      become: yes
      ansible.builtin.package:
        name: "{{ packages_to_install }}"
        state: present

    - name: Change default shell to zsh
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh

    - name: Clone Git repositories
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        depth: 1
      with_items: "{{ git_repos }}"
      
    - name: Debug user directory
      become: no
      ansible.builtin.debug:
        msg: "User directory is {{ ansible_env.HOME }}"
        
    - name: Stow dotfiles
      become: no
      ansible.builtin.command:
        cmd: stow -v -t "{{ ansible_env.HOME }}" -d "{{ ansible_env.HOME }}/dotfiles" "{{ item }}"
      with_items: "{{ stow_items }}"
      
    # TODO: build+install emacs from source
    # ./configure --with-native-compilation --with-imagemagick --with-json --with-tree-sitter --with-xft --with-modules --with-threads --with-x-toolkit=gtk2 --with-zlib --with-jpeg --with-png
    # TODO: add emacs to path
    # - name: Install doom
    #   become: no
    #   ansible.builtin.command:
    #     cmd: "{{ ansible_env.HOME }}/.config/emacs/bin/doom install"
        
    - name: Install miniconda
      become: no
      shell: |
        mkdir -p ~/miniconda3
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
        bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
        rm -rf ~/miniconda3/miniconda.sh
        ~/miniconda3/bin/conda init zsh
      args:
        creates: "{{ ansible_env.HOME }}/miniconda3/bin/conda"

    # todo: 
    # - build and install emacs from source
    #   - see: https://harryrschwartz.com/2022/12/08/how-i-build-emacs-from-source-on-debian
    # - setup doom emacs
    # - stow doom emacs file
    # - setup org-protocol
