[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
formatter = { command = "ruff", args = ["format", "-"] }

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
autoImportCompletions = true
